name: npm test - Module 4 - matrix
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    strategy:
      matrix:
        version: [20, lts/*]
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: '${{ matrix.version }}'
        - name: run install
          shell: bash
          run: |
            cd ./docs
            npm install
            npm test
